### ISSUE TITLE
[copyright infringement] please rename your packages and organisation

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony-util/controller-using-templating-http-foundation-model#2]
Hello,

Naming your organization and your packages with "symfony" in the name might create confusion for the community.

Also Symfony is a trademark that must be used within the policy described at [symfony.com/trademark](https://symfony.com/trademark)

Please rename your organization and all related packages.

Thanks for your understanding.

**Comment by Nardberjean** [comment]
Hello,
Sorry for that. Is utils-for-symfony acceptable?
Based on "Building on Symfony or for Symfony" section.

**Comment by nicolas-grekas** [comment]
Yes that's ok thanks.
